const CATEGORIES = [
  {
    key: 'ordinateurs-serveurs',
    name: 'Ordinateurs & Serveurs',
    slug: 'ordinateurs-serveurs',
    description: "Laptops Pro, PC de bureau et serveurs tour haute disponibilité pour l'ingénierie et la bureautique intensive.",
    icon: 'laptop_mac',
    position: 1
  },
  {
    key: 'videosurveillance',
    name: 'Vidéosurveillance IP',
    slug: 'videosurveillance',
    description: 'Caméras IP 4K, NVR intelligents et dômes PTZ motorisés pour la sécurité électronique professionnelle.',
    icon: 'videocam',
    position: 2
  },
  {
    key: 'reseaux-switchs',
    name: 'Réseaux & Switchs',
    slug: 'reseaux-switchs',
    description: 'Switchs administrables PoE, routeurs et bornes Wi-Fi 6 pour infrastructures réseau haute performance.',
    icon: 'lan',
    position: 3
  },
  {
    key: 'energie-onduleurs',
    name: 'Énergie & Onduleurs',
    slug: 'energie-onduleurs',
    description: 'Onduleurs et solutions de protection électrique pour la continuité de service des salles serveurs.',
    icon: 'bolt',
    position: 4
  },
  {
    key: 'cablage-baies',
    name: 'Câblage & Baies',
    slug: 'cablage-baies',
    description: 'Câblage structuré Cat6/6A, baies de brassage et coffrets muraux pour un déploiement réseau propre.',
    icon: 'settings_ethernet',
    position: 5
  }
];

const PRODUCTS = [
  {
    category: 'ordinateurs-serveurs',
    sku: 'HP-PB450G10-I7',
    name: 'PC Portable HP ProBook 450 G10 (Core i7, 16Go, 512Go SSD)',
    slug: 'pc-portable-hp-probook-450-g10-i7',
    brand: 'HP Enterprise',
    shortDescription: 'Intel Core i7-1355U, 16Go RAM, 512Go SSD NVMe, écran 15.6" FHD antireflet.',
    description: "Intel Core i7-1355U, 16Go RAM, 512Go SSD NVMe, écran 15.6\" FHD antireflet, Windows 11 Professionnel 64 bits. Garantie constructeur 24 mois, idéal pour la bureautique intensive et le déploiement en flotte d'entreprise.",
    specs: { Processeur: 'Intel Core i7-1355U', Mémoire: '16 Go DDR5', Stockage: '512 Go SSD NVMe', Écran: '15.6" FHD antireflet', OS: 'Windows 11 Professionnel', Connectivité: 'Wi-Fi 6E' },
    highlights: ['Intel Gen 13', 'Wi-Fi 6E', 'Garantie 24 mois'],
    priceHt: 407563, priceTtc: 485000, compareAtPriceTtc: null,
    stock: 24, stockAlertThreshold: 5, warrantyMonths: 24, availability: 'in_stock',
    isFeatured: true, isNew: false, ratingAvg: 4.8, ratingCount: 28,
    image: 'laptop'
  },
  {
    category: 'ordinateurs-serveurs',
    sku: 'HP-EB840G9-I7',
    name: 'PC Portable HP EliteBook 840 G9 i7 16Go 512Go SSD',
    slug: 'pc-portable-hp-elitebook-840-g9',
    brand: 'HP Enterprise',
    shortDescription: 'Intel Core i7, 16 Go DDR5, 512 Go NVMe — station ultraportable pour cadres et ingénieurs.',
    description: "Ultraportable professionnel avec châssis renforcé MIL-STD-810H, clavier rétroéclairé et webcam confidentielle. Conçu pour les équipes commerciales et techniques en mobilité.",
    specs: { Processeur: 'Intel Core i7', Mémoire: '16 Go DDR5', Stockage: '512 Go NVMe', Écran: '14" FHD', OS: 'Windows 11 Professionnel' },
    highlights: ['Intel Core i7', '16 Go DDR5', '512 Go NVMe'],
    priceHt: 546218, priceTtc: 650000, compareAtPriceTtc: null,
    stock: 15, stockAlertThreshold: 5, warrantyMonths: 24, availability: 'in_stock',
    isFeatured: false, isNew: false, ratingAvg: 4.6, ratingCount: 18,
    image: 'laptop'
  },
  {
    category: 'ordinateurs-serveurs',
    sku: 'HP-PB450G10-I5',
    name: 'PC Portable HP ProBook 450 G10 (Core i5, 16Go, 512Go SSD)',
    slug: 'pc-portable-hp-probook-450-g10-i5',
    brand: 'HP Enterprise',
    shortDescription: 'Intel Core i5-1335U, 16 Go DDR4, SSD 512 Go NVMe — version économique du ProBook 450.',
    description: 'Version Core i5 du ProBook 450 G10, parfaite pour les déploiements de parc informatique à grande échelle avec un excellent rapport qualité-prix.',
    specs: { Processeur: 'Intel Core i5-1335U', Mémoire: '16 Go DDR4', Stockage: '512 Go SSD NVMe', Écran: '15.6" FHD' },
    highlights: ['Intel Core i5', '16 Go DDR4', 'Stock Douala'],
    priceHt: 353782, priceTtc: 420000, compareAtPriceTtc: null,
    stock: 12, stockAlertThreshold: 5, warrantyMonths: 24, availability: 'in_stock',
    isFeatured: false, isNew: false, ratingAvg: 4.5, ratingCount: 9,
    image: 'laptop'
  },
  {
    category: 'ordinateurs-serveurs',
    sku: 'DELL-PET350-XEON',
    name: 'Serveur Tour Dell PowerEdge T350 Xeon 32Go',
    slug: 'serveur-dell-poweredge-t350',
    brand: 'Dell Technologies',
    shortDescription: 'Intel Xeon E-2336, 32 Go ECC RAM, contrôleur PERC H755 et 2x 2To SAS Entreprise.',
    description: "Serveur tour d'entreprise haute disponibilité, conçu pour l'hébergement d'applications métier, bases de données et virtualisation légère.",
    specs: { Processeur: 'Intel Xeon E-2336', Mémoire: '32 Go ECC', Stockage: '2x 2To SAS', Contrôleur: 'PERC H755' },
    highlights: ['Xeon E-2336', '32 Go ECC', 'RAID PERC H755'],
    priceHt: 1554622, priceTtc: 1850000, compareAtPriceTtc: null,
    stock: 4, stockAlertThreshold: 2, warrantyMonths: 36, availability: 'in_stock',
    isFeatured: false, isNew: true, ratingAvg: 4.9, ratingCount: 6,
    image: 'server'
  },
  {
    category: 'ordinateurs-serveurs',
    sku: 'DELL-PET150-XEON',
    name: 'Serveur Dell PowerEdge T150 Xeon 32Go RAM',
    slug: 'serveur-dell-poweredge-t150',
    brand: 'Dell Technologies',
    shortDescription: 'Intel Xeon E-2314, 32 Go ECC, 2x 2To Enterprise — serveur d\'entrée de gamme robuste.',
    description: 'Serveur compact idéal pour PME et succursales, avec gestion à distance iDRAC9 incluse.',
    specs: { Processeur: 'Intel Xeon E-2314', Mémoire: '32 Go ECC', Stockage: '2x 2To Enterprise', Gestion: 'iDRAC9' },
    highlights: ['Xeon E-2314', '32 Go ECC', 'iDRAC9'],
    priceHt: 966387, priceTtc: 1150000, compareAtPriceTtc: null,
    stock: 3, stockAlertThreshold: 2, warrantyMonths: 36, availability: 'on_order',
    isFeatured: false, isNew: false, ratingAvg: 4.4, ratingCount: 11,
    image: 'server'
  },
  {
    category: 'videosurveillance',
    sku: 'HIK-KIT8-4K-NVR8',
    name: 'Kit 8 Caméras IP Hikvision 4K + NVR 8 Voies PoE',
    slug: 'kit-8-cameras-ip-hikvision-4k-nvr-8-voies',
    brand: 'Hikvision Pro',
    shortDescription: '4K Ultra HD, vision nuit 40m, kit complet prêt à installer.',
    description: 'Kit de vidéosurveillance complet pour sites commerciaux et industriels : 8 caméras IP 4K, NVR 8 voies PoE et câblage inclus.',
    specs: { Résolution: '4K Ultra HD (8MP)', 'Vision nocturne': '40 mètres', Alimentation: 'PoE 802.3af', Canaux: '8 voies' },
    highlights: ['4K Ultra HD', 'Vision Nuit 40m', 'PoE inclus'],
    priceHt: 605042, priceTtc: 720000, compareAtPriceTtc: null,
    stock: 9, stockAlertThreshold: 3, warrantyMonths: 24, availability: 'in_stock',
    isFeatured: true, isNew: false, ratingAvg: 4.7, ratingCount: 19,
    image: 'camera'
  },
  {
    category: 'videosurveillance',
    sku: 'HIK-PACK4K-4CAM-NVR8-2TO',
    name: 'Pack Vidéosurveillance Pro 4K Hikvision - 4 Caméras IP 8MP + NVR 8 Voies PoE 2To HDD',
    slug: 'pack-videosurveillance-pro-4k-hikvision',
    brand: 'Hikvision Pro',
    shortDescription: 'Capteur 4K 8MP, IA AcuSense, IP67, PoE 802.3af — pack complet avec choix de capacité HDD.',
    description: "Solution de sécurité ultra-haute définition conçue pour sièges sociaux, entrepôts logistiques, commerces et résidences d'exception. Résolution native 4K 8 Mégapixels, vision de nuit intelligente jusqu'à 40m, filtrage IA des fausses alertes (humains et véhicules) et alimentation PoE Plug & Play.",
    specs: {
      'Résolution Capteur': '8 Mégapixels 4K Ultra HD (3840×2160 @ 20ips)',
      'Capteur Optique': '1/2.8" Progressive Scan CMOS, focale 2.8mm',
      'IA': 'Hikvision AcuSense 2.0',
      'Vision Nocturne': "Jusqu'à 40m EXIR 2.0",
      'Compression': 'H.265+ / H.265 / H.264+ / H.264',
      'Étanchéité': 'IP67, -30°C à +60°C',
      'Alimentation': 'PoE 802.3af + 12V DC auxiliaire',
      'Canaux NVR': '8 voies IP, 8 ports RJ45 PoE',
      'Sorties': '1x HDMI 4K + 1x VGA',
      'Cloud': 'Hik-Connect P2P, TLS 1.3'
    },
    highlights: ['PoE 802.3af Gigabit', 'Capteur 8MP', 'App Hik-Connect'],
    priceHt: 360170, priceTtc: 425000, compareAtPriceTtc: 480000,
    stock: 6, stockAlertThreshold: 3, warrantyMonths: 24, availability: 'in_stock',
    isFeatured: false, isNew: false, ratingAvg: 4.9, ratingCount: 38,
    image: 'camera',
    variants: [
      { name: '1 To Inclus (~8 jours d\'enregistrement)', sku: 'HIK-PACK4K-HDD1TO', priceDeltaTtc: 0, stock: 6, isDefault: true },
      { name: '2 To Recommandé (~18 jours continus)', sku: 'HIK-PACK4K-HDD2TO', priceDeltaTtc: 35000, stock: 6 },
      { name: '4 To Pro 24/7 (~38 jours d\'archives)', sku: 'HIK-PACK4K-HDD4TO', priceDeltaTtc: 75000, stock: 4 }
    ]
  },
  {
    category: 'videosurveillance',
    sku: 'DAHUA-DOME-IP-4K-IR30',
    name: 'Caméra Dôme IP Dahua 4K WizSense IR 30m',
    slug: 'camera-dome-ip-dahua-4k-wizsense-ir-30m',
    brand: 'Dahua Technology',
    shortDescription: 'Résolution 8MP Ultra HD, détection IA humains/véhicules, IP67/IK10 antivandale.',
    description: 'Caméra dôme robuste pour extérieur, détection intelligente des fausses alarmes et image nette de jour comme de nuit.',
    specs: { Résolution: '4K UHD (8MP)', Étanchéité: 'IP67 / IK10', Alimentation: 'PoE 802.3af', IA: 'Détection humains/véhicules' },
    highlights: ['4K UHD (8MP)', 'IP67 Étanche', 'PoE 802.3af'],
    priceHt: 57023, priceTtc: 68000, compareAtPriceTtc: null,
    stock: 34, stockAlertThreshold: 8, warrantyMonths: 24, availability: 'in_stock',
    isFeatured: false, isNew: false, ratingAvg: 4.7, ratingCount: 42,
    image: 'camera'
  },
  {
    category: 'videosurveillance',
    sku: 'DAHUA-PTZ-4K-25X',
    name: 'Dôme PTZ Dahua 4K WizSense 25x Starlight',
    slug: 'dome-ptz-dahua-4k-wizsense-25x',
    brand: 'Dahua Technology',
    shortDescription: "Tracking automatique par IA, zoom optique 25x, alarme sonore et stroboscope dissuasif.",
    description: 'Caméra PTZ motorisée haute performance pour la surveillance de grands périmètres avec suivi automatique des cibles.',
    specs: { Zoom: 'Optique 25x', IA: 'Tracking automatique', Alarme: 'Sonore + stroboscope' },
    highlights: ['Tracking IA', 'Zoom 25x', 'Starlight'],
    priceHt: 285714, priceTtc: 340000, compareAtPriceTtc: null,
    stock: 7, stockAlertThreshold: 3, warrantyMonths: 24, availability: 'in_stock',
    isFeatured: false, isNew: true, ratingAvg: 4.6, ratingCount: 5,
    image: 'camera'
  },
  {
    category: 'reseaux-switchs',
    sku: 'CISCO-CATALYST-24P-POE',
    name: 'Switch Cisco Catalyst 24 Ports PoE+ 370W Gigabit',
    slug: 'switch-cisco-catalyst-24-ports-poe',
    brand: 'Cisco Systems',
    shortDescription: 'PoE+ 370W, 4x 10G SFP+, administration L2/L3 avancée.',
    description: 'Switch d\'entreprise Cisco Catalyst pour infrastructures réseau critiques, avec redondance et QoS avancée.',
    specs: { Ports: '24 Gigabit PoE+', Budget_PoE: '370W', Uplinks: '4x 10G SFP+' },
    highlights: ['PoE+ 370W', '4x 10G SFP+', 'Garantie 3 ans'],
    priceHt: 798319, priceTtc: 950000, compareAtPriceTtc: null,
    stock: 5, stockAlertThreshold: 5, warrantyMonths: 36, availability: 'in_stock',
    isFeatured: true, isNew: false, ratingAvg: 4.8, ratingCount: 42,
    image: 'switch'
  },
  {
    category: 'reseaux-switchs',
    sku: 'CISCO-CBS350-24P',
    name: 'Switch Administrable Cisco CBS350 24P PoE+',
    slug: 'switch-administrable-cisco-cbs350-24p',
    brand: 'Cisco Systems',
    shortDescription: '24 Ports Gigabit, 195W PoE+, 4x 10G SFP+.',
    description: 'Switch administrable pour PME avec interface web intuitive et VLAN avancés.',
    specs: { Ports: '24 Gigabit', Budget_PoE: '195W', Uplinks: '4x 10G SFP+' },
    highlights: ['24 Ports Gigabit', '195W PoE+', '4x 10G SFP+'],
    priceHt: 332773, priceTtc: 395000, compareAtPriceTtc: null,
    stock: 2, stockAlertThreshold: 5, warrantyMonths: 36, availability: 'in_stock',
    isFeatured: false, isNew: false, ratingAvg: 4.5, ratingCount: 29,
    image: 'switch'
  },
  {
    category: 'reseaux-switchs',
    sku: 'CISCO-CBS250-24P-4G',
    name: 'Switch Cisco CBS250-24P-4G PoE 24 Ports Gigabit',
    slug: 'switch-cisco-cbs250-24p-4g',
    brand: 'Cisco Systems',
    shortDescription: '24 Ports PoE+ (195W), 4 liaisons SFP Gigabit, administration web sécurisée & VLAN.',
    description: 'Switch fiable et économique pour extension réseau PoE avec gestion centralisée.',
    specs: { Ports: '24 PoE+', Budget_PoE: '195W', Uplinks: '4x SFP Gigabit' },
    highlights: ['24 Ports PoE+', 'VLAN', 'Certification Cisco Partner'],
    priceHt: 205882, priceTtc: 245000, compareAtPriceTtc: null,
    stock: 8, stockAlertThreshold: 4, warrantyMonths: 24, availability: 'in_stock',
    isFeatured: false, isNew: false, ratingAvg: 4.6, ratingCount: 14,
    image: 'switch'
  },
  {
    category: 'reseaux-switchs',
    sku: 'MIKROTIK-CRS328-24P',
    name: 'MikroTik CRS328 24P PoE+ Dual Boot RouterOS',
    slug: 'mikrotik-crs328-24p-poe',
    brand: 'MikroTik Networks',
    shortDescription: 'Routeur/switch rackable professionnel, alimentation 500W et 4 cages SFP+ 10Gbps.',
    description: 'Équipement polyvalent RouterOS/SwitchOS pour opérateurs et intégrateurs télécoms.',
    specs: { Ports: '24 PoE+', Uplinks: '4x SFP+ 10Gbps', Alimentation: '500W' },
    highlights: ['Dual Boot RouterOS', '500W', '4x SFP+ 10G'],
    priceHt: 348739, priceTtc: 415000, compareAtPriceTtc: null,
    stock: 6, stockAlertThreshold: 3, warrantyMonths: 24, availability: 'in_stock',
    isFeatured: false, isNew: true, ratingAvg: 4.5, ratingCount: 8,
    image: 'switch'
  },
  {
    category: 'reseaux-switchs',
    sku: 'MIKROTIK-CCR-CORE',
    name: 'MikroTik CCR2004 Routeur Cloud Core 1Gbps',
    slug: 'mikrotik-ccr2004-routeur-cloud-core',
    brand: 'MikroTik Networks',
    shortDescription: 'Routeur cœur de réseau haute performance pour opérateurs et grandes entreprises.',
    description: 'Routeur Cloud Core dédié au routage inter-VLAN et à la sécurité périmétrique pour architectures réseau complexes.',
    specs: { Débit: '1 Gbps', Ports: '4x SFP+', CPU: '16 coeurs ARM' },
    highlights: ['Cloud Core', 'Haute Dispo', '16 coeurs'],
    priceHt: 235294, priceTtc: 280000, compareAtPriceTtc: null,
    stock: 5, stockAlertThreshold: 3, warrantyMonths: 24, availability: 'in_stock',
    isFeatured: false, isNew: false, ratingAvg: 4.4, ratingCount: 7,
    image: 'switch'
  },
  {
    category: 'reseaux-switchs',
    sku: 'SW-8P-POE-120W',
    name: 'Switch Gigabit PoE+ 8 Ports 120W - Gestion Intelligente',
    slug: 'switch-gigabit-poe-8-ports-120w',
    brand: 'AUTS Networks',
    shortDescription: 'Pour étendre le réseau ou déporter des caméras jusqu\'à 250 mètres en mode surveillance étendue.',
    description: 'Switch compact idéal en complément d\'un kit de vidéosurveillance ou pour un petit bureau.',
    specs: { Ports: '8 Gigabit PoE+', Budget_PoE: '120W', Portée_étendue: '250m' },
    highlights: ['Gigabit PoE+', '120W', 'Mode surveillance étendue'],
    priceHt: 48739, priceTtc: 58000, compareAtPriceTtc: null,
    stock: 14, stockAlertThreshold: 5, warrantyMonths: 12, availability: 'in_stock',
    isFeatured: false, isNew: false, ratingAvg: 4.3, ratingCount: 4,
    image: 'switch'
  },
  {
    category: 'energie-onduleurs',
    sku: 'APC-SMARTUPS-1500VA',
    name: 'Onduleur APC Smart-UPS 1500VA LCD 230V',
    slug: 'onduleur-apc-smart-ups-1500va',
    brand: 'APC by Schneider',
    shortDescription: 'Onde pure sinusoïdale, SmartConnect, écran LCD, régulation AVR.',
    description: 'Protection électrique pour baies serveurs et équipements réseau sensibles, avec supervision à distance SmartConnect.',
    specs: { Puissance: '1500VA / 900W', Onde: 'Pure sinusoïdale', Écran: 'LCD', Supervision: 'SmartConnect' },
    highlights: ['Pure Sine Wave', 'SmartConnect', 'LCD'],
    priceHt: 306722, priceTtc: 365000, compareAtPriceTtc: null,
    stock: 11, stockAlertThreshold: 4, warrantyMonths: 24, availability: 'in_stock',
    isFeatured: true, isNew: false, ratingAvg: 4.7, ratingCount: 34,
    image: 'ups'
  },
  {
    category: 'energie-onduleurs',
    sku: 'APC-SMARTUPS-750VA',
    name: 'Onduleur APC Smart-UPS 750VA Rack 2U',
    slug: 'onduleur-apc-smart-ups-750va-rack',
    brand: 'APC by Schneider',
    shortDescription: 'Format rack 2U, régulation AVR intégrée, idéal pour baies de brassage compactes.',
    description: 'Solution de continuité électrique compacte pour baies réseau de petite et moyenne taille.',
    specs: { Puissance: '750VA / 500W', Format: 'Rack 2U', Régulation: 'AVR' },
    highlights: ['Rack 2U', 'AVR intégré', 'Compact'],
    priceHt: 193277, priceTtc: 230000, compareAtPriceTtc: null,
    stock: 9, stockAlertThreshold: 4, warrantyMonths: 24, availability: 'in_stock',
    isFeatured: false, isNew: false, ratingAvg: 4.5, ratingCount: 10,
    image: 'ups'
  },
  {
    category: 'cablage-baies',
    sku: 'CAT6A-SFTP-500M',
    name: 'Touret 500m Câble Cat 6A SFTP 100% Cuivre',
    slug: 'touret-500m-cable-cat6a-sftp',
    brand: 'Nexans',
    shortDescription: 'Double blindage tresse + alu, gaine LSZH anti-incendie, certifié Fluke Networks.',
    description: 'Câble réseau haute performance pour infrastructures 10 Gigabit, certifié pour les environnements exigeants.',
    specs: { Catégorie: 'Cat 6A SFTP', Longueur: '500m', Gaine: 'LSZH anti-feu' },
    highlights: ['100% Cuivre', 'LSZH anti-feu', 'Certifié Fluke'],
    priceHt: 163866, priceTtc: 195000, compareAtPriceTtc: null,
    stock: 18, stockAlertThreshold: 5, warrantyMonths: 12, availability: 'in_stock',
    isFeatured: false, isNew: true, ratingAvg: 4.6, ratingCount: 3,
    image: 'cabling'
  },
  {
    category: 'cablage-baies',
    sku: 'CAT6-UTP-100M',
    name: 'Bobine Câble Réseau Cat6 UTP Cuivre Intérieur/Extérieur 100m',
    slug: 'bobine-cable-reseau-cat6-utp-100m',
    brand: 'Nexans',
    shortDescription: 'Zéro perte de signal vidéo 4K, excellente conduction PoE continue sur longue distance.',
    description: 'Câblage polyvalent intérieur/extérieur pour déploiements de caméras IP et postes de travail.',
    specs: { Catégorie: 'Cat 6 UTP', Longueur: '100m', Usage: 'Intérieur/Extérieur' },
    highlights: ['100% Cuivre Pur', 'PoE stable', 'Intérieur/Extérieur'],
    priceHt: 27311, priceTtc: 32500, compareAtPriceTtc: null,
    stock: 48, stockAlertThreshold: 15, warrantyMonths: 12, availability: 'in_stock',
    isFeatured: false, isNew: false, ratingAvg: 4.4, ratingCount: 6,
    image: 'cabling'
  },
  {
    category: 'cablage-baies',
    sku: 'COFFRET-MURAL-6U',
    name: 'Coffret Mural Informatique 6U 19\'\' - Porte Verre avec Serrure',
    slug: 'coffret-mural-informatique-6u-19',
    brand: 'AUTS Networks',
    shortDescription: 'Protège NVR et switchs contre le vol, les déconnexions malveillantes et la poussière tropicale.',
    description: 'Baie murale compacte avec porte vitrée verrouillable, ventilation intégrée et passe-câbles.',
    specs: { Format: '6U 19"', Porte: 'Verre avec serrure', Ventilation: 'Intégrée' },
    highlights: ['Sécurité 19 Pouces', 'Porte verrouillable', 'Prêt à installer'],
    priceHt: 58024, priceTtc: 69000, compareAtPriceTtc: null,
    stock: 10, stockAlertThreshold: 4, warrantyMonths: 12, availability: 'in_stock',
    isFeatured: false, isNew: false, ratingAvg: 4.5, ratingCount: 7,
    image: 'cabling'
  }
];

module.exports = { CATEGORIES, PRODUCTS };
